name: CI

on:
    workflow_dispatch:

jobs:
    build-nuget:
        name: Build NuGet package
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Add Intel oneAPI APT repo
              run: |
                sudo apt-get update
                sudo apt-get install -y gpg-agent wget
                wget -O- https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB | gpg --dearmor | sudo tee /usr/share/keyrings/oneapi-archive-keyring.gpg > /dev/null
                echo "deb [signed-by=/usr/share/keyrings/oneapi-archive-keyring.gpg] https://apt.repos.intel.com/oneapi all main" | sudo tee /etc/apt/sources.list.d/oneAPI.list
                sudo apt-get update
                sudo apt-get install intel-oneapi-mkl intel-oneapi-mkl-devel

            - name: Install required packages
              run: sudo apt-get install -y g++ g++-multilib libc6-dev-i386

            - name: Debug
              run: |
                ls -la /opt
                ls -la /opt/intel
                ls -la /opt/intel/oneapi
                ls -la /opt/intel/oneapi/mkl/
                echo "---- latest version ----"
                readlink /opt/intel/oneapi/mkl/latest
                realpath /opt/intel/oneapi/mkl/latest
                echo ""
                echo ""
                echo ""
                echo ""
                ls -la /opt/intel/oneapi/compiler
                ls -la /opt/intel/oneapi/compiler/2025.2
                ls -la /opt/intel/oneapi/compiler/2025.2/lib


            - name: Build NuGet package
              working-directory: src/NativeProviders/Linux
              run: |
                #!/bin/bash

                set -e
                export VERSION=$(readlink /opt/intel/oneapi/mkl/latest)
                export INTEL=/opt/intel
                export MKL=$INTEL/oneapi/mkl/$VERSION
                export OPENMP=$INTEL/oneapi/compiler/$VERSION/lib
                export OUT=../../../out/MKL/Linux

                mkdir -p $OUT/x64
                mkdir -p $OUT/x86

                g++ -std=c++11 -D_M_X64 -DGCC -m64 --shared -fPIC -o $OUT/x64/libMathNetNumericsMKL.so -I$MKL/include -I../Common -I../MKL ../MKL/memory.c ../MKL/capabilities.cpp ../MKL/vector_functions.c ../Common/blas.c ../Common/lapack.cpp ../MKL/fft.cpp -Wl,--start-group  $MKL/lib/intel64/libmkl_intel_lp64.a $MKL/lib/intel64/libmkl_intel_thread.a $MKL/lib/intel64/libmkl_core.a -Wl,--end-group -L$OPENMP/intel64_lin -liomp5 -lpthread -lm

                cp $OPENMP/intel64_lin/libiomp5.so  $OUT/x64/

                g++ -std=c++11 -D_M_IX86 -DGCC -m32 --shared -fPIC -o $OUT/x86/libMathNetNumericsMKL.so -I$MKL/include -I../Common -I../MKL ../MKL/memory.c ../MKL/capabilities.cpp ../MKL/vector_functions.c ../Common/blas.c ../Common/lapack.cpp ../MKL/fft.cpp  -Wl,--start-group $MKL/lib/ia32/libmkl_intel.a $MKL/lib/ia32/libmkl_intel_thread.a $MKL/lib/ia32/libmkl_core.a -Wl,--end-group -L$OPENMP/ia32_lin -liomp5 -lpthread -lm

                cp $OPENMP/ia32_lin/libiomp5.so  $OUT/x86/

            - name: Debug
              run: |
                ls -la out

#    publish-release:
#        name: Publish nuget package to NuGet
#        runs-on: ubuntu-latest
#        permissions:
#            contents: write
#        steps:
#            - name: Checkout
#              uses: actions/checkout@v4
#            - name: Check version
#              id: check-version
#              shell: pwsh
#              run: |
#                  $version = "${{ needs.build-nuget.outputs.version }}"
#                  $tag = "${{ github.ref }}".SubString(10)
#                  if (-not ($tag -eq $version)) {
#                    echo "::error ::There is a mismatch between the project version ($version) and the tag ($tag)"
#                    exit 1
#                  }
#            - name: Download NuGet artifact
#              uses: actions/download-artifact@v4
#              with:
#                  name: nuget-package
#                  path: nuget
#            - name: Setup .NET SDK v8.0.x
#              uses: actions/setup-dotnet@v4
#              with:
#                  dotnet-version: 8.0.x
#
#            - name: Create release
#              uses: softprops/action-gh-release@v2
#              with:
#                  name: ParquetSharp ${{ needs.build-nuget.outputs.version }}
#                  draft: true
#                  prerelease: ${{ contains(needs.build-nuget.outputs.version, '-') }}
#                  files: |
#                      nuget/ParquetSharp.${{ needs.build-nuget.outputs.version }}.nupkg
#              env:
#                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#            - name: Publish to NuGet
#              run: dotnet nuget push nuget/ParquetSharp.${{ needs.build-nuget.outputs.version }}.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
